import Container from "@/components/layout/container/container";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms and Conditions | OrkaTool",
  description:
    "Read OrkaTool's Terms and Conditions outlining website usage policies, calculator tool disclaimers, user responsibility parameters, and limitation of liability clauses.",
  alternates: {
    canonical: "/terms",
  },
};

export default function TermsPage() {
  const lastUpdated = "2026-07-16";

  return (
    <main className="content-page">
      <Container>
        <div className="content-page-body">
          <h1 className="content-page-title" style={{ textAlign: "left", marginBottom: "0.5rem" }}>Terms & Conditions</h1>
          <p className="content-page-last-updated">
            Last Updated: {lastUpdated}
          </p>

          <div className="content-page-sections">
            <section>
              <h2 className="content-page-section-title">
                1. Acceptance of Terms
              </h2>
              <p>
                By visiting and using OrkaTool (the &quot;Website&quot;), you consent to and agree to stay bound by these Terms and Conditions. If you do not accept these criteria in full, do not continue to use the site utilities.
              </p>
            </section>

            <section>
              <h2 className="content-page-section-title">
                2. Calculation & Tool Disclaimer
              </h2>
              <p className="content-page-disclaimer">
                <strong>Disclaimer of Financial/Professional Advice:</strong> The values, parameters, and results generated by OrkaTool including but not limited to the Zakat Calculator are for educational and information purposes only. They do not constitute financial, legal, tax, or religious expert advice. Always verify calculations with professional experts before committing actual finances.
              </p>
            </section>

            <section>
              <h2 className="content-page-section-title">
                3. Tool Accuracy Limits
              </h2>
              <p>
                While we strive to implement robust testing, OrkaTool cannot guarantee all mathematical engines, data indices, conversion formulas, or outputs contain absolute accuracy. Users rely on these tools entirely at their own discretion.
              </p>
            </section>

            <section>
              <h2 className="content-page-section-title">
                4. Permitted Website Usage
              </h2>
              <p>
                Our services are granted free for personal use or administrative assistance. You may not deploy automated scraping scripts, Denial of Service (DoS) queries, or malicious bots attempting to alter site performance, assets, or server routing.
              </p>
            </section>

            <section>
              <h2 className="content-page-section-title">
                5. Copyright & Ownership
              </h2>
              <p>
                The OrkaTool visual design, themes, layouts, interface code components, logos, and custom copy represent proprietary intellectual assets and are protected by international trademark and licensing conventions.
              </p>
            </section>

            <section>
              <h2 className="content-page-section-title">
                6. Limitation of Liability
              </h2>
              <p>
                To the fullest extent legally permissible, OrkaTool and its development team shall not act liable for any circumstantial losses, errors, transactional damage, or data disruptions arising out of your utilization of calculation tools.
              </p>
            </section>

            <section>
              <h2 className="content-page-section-title">
                7. Terms Modifications
              </h2>
              <p>
                We reserve full rights to adjust these Terms and Conditions guidelines at any period without prior advisory broadcasts. Revised documents become active instantly upon updates to this page.
              </p>
            </section>

            <section>
              <h2 className="content-page-section-title">
                8. Contact Info
              </h2>
              <p>
                For questions regarding accepting these Terms, contact us by email: <strong>support@orkatool.com</strong>.
              </p>
            </section>
          </div>
        </div>
      </Container>
    </main>
  );
}
